repos:
-   repo: [https://github.com/antonbabenko/pre-commit-terraform](https://github.com/antonbabenko/pre-commit-terraform)
    rev: v1.88.0
    hooks:
    -   id: terraform_fmt
    -   id: terraform_docs
    -   id: terraform_tflint